### ISSUE TITLE
Windows: Using inline-c in combination with hsc2hs generates the .c files with bad paths

### ISSUE THREAD

**Issue by rcook** [fpco/inline-c#50] opened 2016-08-20 04:21 UTC
Repro steps:
- Install Stack on a _Windows_ development machine.
- Create new simple project with `stack new inlinecbug simple`.
- Rename `src/Main.hs` to `src/Main.hsc` in the `inlinecbug` project directory.
- Build project with `stack build` and run with `stack exec inlinecbug` to verify that hsc2hs works correctly.
- Replace content of `src/Main.hsc` with following:

``` haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}

import qualified Language.C.Inline as C

C.include "<math.h>"

main :: IO ()
main = do
  x <- [C.exp| double{ cos(1) } |]
  print x
```
- In `inlinecbug.cabal` add `inline-c` to the `build-depends` section of `executable inlinecbug`.
- Add the line `c-sources: src/Main.c` to the `executable inlinecbug` section.
- Rebuild with `stack build`.

Build will fail with a linker error referring to a undefined reference to an `inline_c_main...` function. List the files in the root directory of the project and you'll see that inline-c has generated a file with the name `srcMain.c`: i.e. the backslashes in the Windows path have been removed.

Building under Linux generates the C output file with the correct, expected path of `src/Main.c` and the program will compile, link and run as expected.

See also: https://ghc.haskell.org/trac/ghc/ticket/12504

**Comment by mgsloan** [comment] 2016-08-20 07:37
I actually encountered a related issue recently.  Check out this commit in stack - https://github.com/commercialhaskell/stack/commit/1ffae897b1441d4b2b4502c5c22eb442027ab96a - the reason this was necessary is that the paths were like `src/Stack\Main.hs`!  So, mixed forward and backward slashes.  On linux the paths were absolute not relative.  So it is likely a ghc issue, possibly a Cabal issue.

The resolution is to modify `cSourceLoc`, [here](https://github.com/fpco/inline-c/blob/24020e1cd4d9196fde125ea7e957d633d5b49717/src/Language/C/Inline/Internal.hs#L180), to fix the slashes.  Are there any circumstances where we wouldn't want to do something like `replace "/" "\\"` on windows.  I don't think there are.

**Comment by rcook** [comment] 2016-08-20 08:02
It looks like the backslashes have already been removed at this point: `TH.loc_filename` returns the invalid path. Maybe the bug is in Template Haskell?

**Comment by mgsloan** [comment] 2016-08-20 08:08
Likely so!  It probably does something like `include_dir ++ "/" ++ source_path` orso

**Comment by awson** [comment] 2016-08-20 17:21
The culprit is `{-# LINE ...  #-}` pragmas in the files generated by `hsc2hs`. `hsc2hs` on Windows emits paths with non-escaped backslashes in it:
```
{-# LINE 1 "src\Language\C\Clang\Internal\FFI.hsc" #-}
```
I don't know how GHC's `LINE` pragma behavior is specified, but this is at least inconsistent with how Windows C compilers operate. GCC emits line directives with forward slashes in paths and Visual C emits escaped backslashes. Thus I mostly inclined to treat this as bug in `hsc2hs` (easily fixable).

**Comment by rcook** [comment] 2016-08-20 17:47
Thanks @awson. I added your comment to the GHC bug: https://ghc.haskell.org/trac/ghc/ticket/12504#comment:1

**Comment by bitonic** [comment] 2016-08-22 08:23
Thanks a lot for the investigation.

I have little experience with Windows Haskell development, and it's not totally clear if `inline-c` can mitigate this GHC/TH bug. If we can I'm happy to get my feet wet with Windows + Haskell (which I have installed just to play games), but I'm not sure that there is anything to do at all.

**Comment by awson** [comment] 2016-08-22 08:55
I don't think GHC behavior is wrong here.

I haven't seen anywhere how GHC expects a file path in the LINE pragma to be formatted, but as I've already mentioned above, well-established practice is to expect it to have either forward slashes or escaped backslashes (or both). If GHC is supplied with such formatted paths it works perfectly on Windows. Thus, I think we shouldn't touch GHC proper.

It is `hsc2hs` which is wrong.
[Look at `outHsLine` function](https://git.haskell.org/hsc2hs.git/blob/HEAD:/C.hs#l188): it looks as being ok, since `showCString` escapes backslashes. But the problem is that `hsc_line` which is `printf` in disguise, eats these escapes back, and finally outputs backslashes unescaped.

I created a tiny patch which flips escaped backslashes to forward slashes in `outHsLine` after `showCString` is applied and tested it having built `inline-c` on Windows. Things went without a hitch.

**Comment by rcook** [comment] 2016-08-22 17:20
@awson: So, it looks like there are two interwoven issues here:

1. `outHsLine` does not properly escape the format string passed to `hsc_line`
2. `outHsLine` should probably normalize to forward slashes regardless of the platform

The resulting code would probably look something like:

```haskell
outHsLine :: SourcePos -> String
outHsLine (SourcePos name line) =
    "    hsc_line (" ++ show (line + 1) ++ ", \"" ++
    (showCString . showCString . normalizePath) name ++"\");\n"

normalizePath :: FilePath -> FilePath
#ifdef mingw32_HOST_OS
normalizePath = map escapeChar
    where escapeChar '\\' = '/'
          escapeChar c = id c
#else
normalizePath = id
#endif
```

i.e. Normalize the path first and then escape the string as a C string literal twice.

What do you think ? If this looks reasonable to you, I'll see if I can make the fix in hsc2hs myself.

**Comment by awson** [comment] 2016-08-22 18:44
I don't think we need to apply `showCString` twice.

`showCString` is here exactly to double-escape things to make things good after `printf` eats this extra layer of escaping and it does this pretty well.

What is happen here is that we need to make some extra work **only when generating path names on Windows**, since the single backslash in the windows path in `LINE` directive is wrong. Thus we should either to double this backslash or replace it with a forward slash.

Thus I believe `(showCString . normalizePath)` would suffice here. And also after some thinking I believe your proposal to flip slashes before applying `showCString` is more ideologically correct than mine although I believe both would work well in real-world scenarios.

**Comment by rcook** [comment] 2016-08-22 19:12
@awson: Agreed.

**Comment by rcook** [comment] 2016-08-26 22:15
I've submitted a new test case:
https://phabricator.haskell.org/D2477

And the code fix itself:
https://phabricator.haskell.org/D2478

**Comment by bitonic** [comment] 2016-09-01 07:50
Just to be clear: is this purely a GHC issue, and will it be automatically resolved when GHC 8.0.2 is out?

**Comment by rcook** [comment] 2016-09-01 19:11
@bitonic : Yes, that's right. The fix will be included in the new version of hsc2cs that will ship with GHC 8.0.2. Feel free to close this ticket as appropriate.

**Comment by ekmett** [comment] 2019-06-03 14:51
This appears to be resolved.

**Comment by bitonic** [comment] 2019-06-03 18:28
@ekmett thanks for checking, closing

**Closed by bitonic** 2019-06-03 18:28 UTC
Labels: bug
